import os

BETFAIR_APP_KEY = os.getenv('BETFAIR_APP_KEY')
BETFAIR_USERNAME = os.getenv('BETFAIR_USERNAME')
BETFAIR_PASSWORD = os.getenv('BETFAIR_PASSWORD')

BETFAIR_CRT_LOC = os.getenv('BETFAIR_CRT_LOC')
BETFAIR_KEY_LOC = os.getenv('BETFAIR_KEY_LOC')
